# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  app:
    container_name: front-server
    image: yawnak/foodadvisor-front:v0.1.2
    ports:
      - '80:80'
    networks:
      - learning

networks:
  learning:
    driver: bridge